### ISSUE TITLE
__security_check_cookie error with QT

### ISSUE THREAD

**Issue by xiaohua4758** [ubawurinna/freetype-windows-binaries#7]
Hi, i use the "release static\win32\freetype.lib"
when build my project, it says:
.....objs\Win32\Release Static\ftbase.obj):-1: error: undefined reference to `@__security_check_cookie@4'
then i can't go on. is this the freetype.lib problem?
Thanks
My environment: Qt Creator 3.5.1(32Bit)
PC: Windows 7 (64Bit)

**Comment by ubawurinna** [comment]
My advice, never use a static library in your projects.
You get this error because the static library is compiled under MSVC with the /GS (Buffer Security Check) switch.
If you really want to use static libraries everything should be compiled with the same compiler version.

With Qt you have to use Qt MSVC 2015/2017/2019 instead of Qt MinGW.

But I rather advise you to use dynamic loading with the libraries and dll present in 'release dll'
